### ISSUE TITLE
ideias para melhorar ainda mais o guiafoca

### ISSUE THREAD

**Issue by ghost** [guiafoca/guiafoca#8]
Olá a todos! 

Eu tenho 5 ideias interessantes e gostaria da opinião de todo mundo aqui do guiafoca. Gostaria de ajudar a contribuir com o guiafoca com essas 5 ideias:
- Criar uma versão do guia foca em slideshow, seria tipo uma imagem, onde o usuário passa o mouse e ler.
- Adicionar informações sobre drivers e hardware compatívies com linux no GuiaFoca: Gostaria de saber se gostariam de adicionar a informação sobre drivers e hardware compatíveis com linux no guiafoca. Um bom exemplo dessa lista de informação sobre drivers e hardware compatíveis com linux seria esse repositório: [linuxhw/SMART](https://github.com/linuxhw/SMART) e [linux-hardware](https://linux-hardware.org). 
- criar quiz(pergunta e resposta) sobre o guiafoca.
- criar apostila guiafoca.
- criar versão guiafoca em docsify.

*Caso achem boa alguma dessas ideia, poderia ajudar caso queiram.*

**Comment by brpgit2024** [comment]
Mas o Guia foca não foi criado por Glaydson Mizoli?

**Comment by ghost** [comment]
Oi brpgit2022, obrigado pelo feedback.

> Mas o Guia foca não foi criado por Glaydson Mizoli?

Então, estava pensando em contribuir com esse projeto.

**Comment by brpgit2024** [comment]
MAS O GLAYDSON DO GUIA FOCA SABE QUE VC FEZ UM FORK DO PROJETO E QUE TEM O MEMO NOME?

**Comment by ghost** [comment]
Oi brpgit2022, valeu pelo feedback novamente.

> MAS O GLAYDSON DO GUIA FOCA SABE QUE VC FEZ UM FORK DO PROJETO E QUE TEM O MEMO NOME?

Achei que seria interessante além de abrir um issue falar com ele se a ideia é boa ou não. Eu não sei se deveria mudar o nome por isso abrir a issue. Assim como, sou iniciante no git e não sei muito sobre a ferramenta, achei interessante somente fazer um fork e abrir um issue aqui para verificar como posso proceder antes de codificar. 

Então... o que você acha da minha ideia? O que você pensa da minha ideia?

**Comment by brpgit2024** [comment]
CARA O PROJETO SEGUE O MOVIMENTO OPENSOURCE MAS PELOMENOS AVISE  ELE E DIZ NO COMEÇO DO LIVRO QUE FOI INSPIRADO NO PROJETO ORIGINAL DO GLADYSON MIZOLI  DO GUIA  FOCA!

**Comment by brpgit2024** [comment]
ACHO TAMBEM QUE DEVERIA MUDAR O NOME TMBM! SEJA ORIGINAL!

**Comment by ghost** [comment]
Oi brpgit2022, valeu pelas informações.
 
> CARA O PROJETO SEGUE O MOVIMENTO OPENSOURCE MAS PELOMENOS AVISE ELE E DIZ NO COMEÇO DO LIVRO QUE FOI INSPIRADO NO PROJETO ORIGINAL DO GLADYSON MIZOLI DO GUIA FOCA!

Como aviso ele? como funciona o "movimento open source"? *(Não entendi o que você quis dizer com seguir o movimento opensource, o que significa seguir o movimento opensource?)*

**Nota:** Não quero mudar nada apenas adicionar um slideshow e adicionar informações de hardware no site do guia-foca seria modificações para main principal desse projeto, seria meu PR. 

*Como posso falar sobre essas ideias aqui? Como posso seguir o movimento opensource?*

**Comment by ghost** [comment]
Oi brpgit2022, valeu pelas informações.

> ACHO TAMBEM QUE DEVERIA MUDAR O NOME TMBM! SEJA ORIGINAL!

valeu por essa dica.

**Comment by brpgit2024** [comment]
VOU TE DAR AS INFORMAÇÕES:

TWITTER:  @guiafoca  @gleydsonmazioli
INSTAGRAM: @guiafoca /  @gleydsonmazioli
GIT: github.com/guiafoca.

TA AI OS CONTATOS.

**Comment by ghost** [comment]
Oi brpgit2022, novamente obrigado pelas informações e pela paciência em responder minhas dúvidas.

**Comment by brpgit2024** [comment]
SÓ MAIS UMA COISA FAZ A COISAS CERTAS!

**Comment by ghost** [comment]
Oi brpgit2022. Poderia me ajudar?

>  SÓ MAIS UMA COISA FAZ A COISAS CERTAS!

- O que isso significa? 
- O que quis dizer com "Só mais uma coisa faz a coisas certas"? 
- o que é certo e o que é errado? 
- como fazer o certo? como não fazer o certo? 

*(Bem... não entendi o que você quis dizer, essas são minhas dúvidas reais. De qualquer forma, caso possa esclarecer essas dúvidas ficaria feliz por sua resposta. Só gostaria de enviar um PR sobre as ideias e vê se a comunidade guiafoca utiliza)*

**Comment by brpgit2024** [comment]
QUIS DIZER QUE ANTES DE VC INICIAR UM PROJETO VC TEM VER SE JÁ NÃO TEM UM PROJETO COM O MESMO NOME OU COM IDEIAS PARECIDO, SE TIVER PERGUNTE SE VC PODE CONTRIBUIR COM A SUA EXPERIÊNCIA! É ISSO QUE EU QUERIA DIZER. NÃO DESMERECENDO VOCÊ MAS É O CORRETO E HONESTO!

**Comment by ghost** [comment]
Oi brpgit2022.

> QUIS DIZER QUE ANTES DE VC INICIAR UM PROJETO VC TEM VER SE JÁ NÃO TEM UM PROJETO COM O MESMO NOME OU COM IDEIAS PARECIDO, SE TIVER PERGUNTE SE VC PODE CONTRIBUIR COM A SUA EXPERIÊNCIA! É ISSO QUE EU QUERIA DIZER. NÃO DESMERECENDO VOCÊ MAS É O CORRETO E HONESTO!

Foi o que falei anteriormente. Olha o que eu disse: - *"Eu tenho 2 ideias interessantes e gostaria da opinião de todo mundo aqui do guiafoca. Gostaria de ajudar a contribuir com o guiafoca com essas duas ideias: ..."*

**Comment by brpgit2024** [comment]
HUM OK

**Comment by ghost** [comment]
Oi brpgit2022.

>  HUM OK

O que acha das ideias que falei? são boas ou ruins? *Digo essas duas ideias:*

- "Criar uma versão do guia foca em slideshow, seria tipo uma imagem, onde o usuário passa o mouse e ler."
- "Adicionar informações sobre drivers e hardware compatívies com linux no GuiaFoca: Gostaria de saber se gostariam de adicionar a informação sobre drivers e hardware compatíveis com linux no guiafoca. Um bom exemplo dessa lista de informação sobre drivers e hardware compatíveis com linux seria esse repositório: [linuxhw/SMART](https://github.com/linuxhw/SMART) e [linux-hardware](https://linux-hardware.org/)."

O que você acha dessas ideias acima?
O que significa HUM OK? Você acha interessante essas duas ideias que listei?

*(Bem... não entendi o que você quis dizer, essas são minhas dúvidas reais. De qualquer forma, caso possa esclarecer essas dúvidas ficaria feliz por sua resposta. Só gostaria de enviar um PR sobre as ideias e vê se a comunidade guiafoca utiliza)*
